# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: caa438a750a67326140916bd1225410361ef7324b77d96d20c92be454eda4abc305dabbbb4a77552ef28ac4d0dae26a3a06a41ea91ad247bfadfbd7add3abf8d

test:
  secret_key_base: d01113ed359560b6cff0a1ba21b73c6fa13f81ae0a3c0df0ef3a6b9ca99093d6e699b9ad5408ce1081b6738a8652c4befd9282f6b9dad789776fbe5faef3bb36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
